[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_exchange_hub = "4VPiS6RyDfAooQyxfW2sbjaEFENCKLTSsVwoiEz8tEZm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/kentstephen/repository/sbc-workspace/key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
